on: [push, pull_request]

name: CI
jobs:
  test:
    strategy:
      matrix:
        go: [ '1.21' ]
        os: [ ubuntu-latest, macos-latest, windows-latest ]
      fail-fast: false

    runs-on: ${{ matrix.os }}
    name: Test suite

    steps:
      - uses: actions/checkout@v4
      - name: Setup go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}
      - run: go test -v ./...
